apiVersion: platform.psi/2026-03-01
kind: component
id: filter-drawer-header
name: Filter Drawer Header
spec:
  type: Text
  pageRef: page:home
  parentRef: frameSurface:filter-drawer
  slotName: header
  layout:
    desktop:
      x: 0
      y: 0
      width: 14
      height: 4
    mobile:
      x: 0
      y: 0
      width: 14
      height: 4
  properties:
    text: Filters
  display:
    showOnDesktop: true
    showOnMobile: false
  validation: {}
