apiVersion: platform.psi/2026-03-01
kind: frameSurface
id: detail-drawer
name: Detail Drawer
spec:
  type: DrawerFrame
  global: false
  pageRef: page:home
  slotName: default
  childOrder:
    - component:detail-drawer-header
    - component:detail-drawer-body
  hidden: true
  showInEditor: true
  showOverlay: true
  overlayInteraction: true
  hideOnEscape: true
  loading: false
  width: medium
  customWidth: null
  padding: normal
  showHeader: true
  showFooter: false
  showHeaderBorder: true
  showFooterBorder: true
  showOnDesktop: true
  showOnMobile: false
