apiVersion: platform.psi/2026-03-01
kind: event
id: open-hidden-editor-drawer-click
name: Open Hidden Editor Drawer Click
spec:
  sourceRef: component:open-hidden-editor-drawer
  sourceSurface: component
  trigger: onClick
  actions:
    - kind: controlComponent
      targetRef: frameSurface:hidden-editor-drawer
      componentActionHandle: show
      componentActionParams: {}
  policyRefs:
    - policy:workspace-reader
