apiVersion: platform.psi/2026-03-01
kind: event
id: open-detail-drawer-click
name: Open Detail Drawer Click
spec:
  sourceRef: component:open-detail-drawer
  sourceSurface: component
  trigger: onClick
  actions:
    - kind: controlComponent
      targetRef: frameSurface:detail-drawer
      componentActionHandle: show
      componentActionParams: {}
  policyRefs:
    - policy:workspace-reader
